<a href="https://colab.research.google.com/github/Njau13/incidents/blob/main/incidents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IT Incident Intelligence Dashboard & Prediction System

##Exploratory Data Analysis

In [ ]:
import pandas as pd
df=pd.read_excel("AnonymizedTickets1.xlsx")

In [ ]:
df.head()

,Incident ID,Priority,Incident Type,Country,Status,Service,Reported Date,Resolved Date,Resolution Time(Minutes),Resolution Time(Hours),Resolution hours,Assignee,Impact,OldPriority,Reported Source,SLM Real Time Status,Submitter*,Summary*,Support Group Name
0,INC001,3-Medium,Incident,Australia,Resolved,NAP PROD AU,6/2/2026 8:31:40 PM,6/2/2026 8:54:42 PM,23.033333,0.383889,0h 23m,Sowmiya E,3-Moderate/Limited,NaN,Monitoring Event,Within the Service Target,ashley.njau,CMOZ | Delta scoring is running longer than usual,ServiceDesk OPS-XFNC SD
1,INC002,3-Medium,Incident,Brazil,Assigned,PROD BR,6/2/2026 8:21:18 PM,NaN,NaN,NaN,NaN,NaN,3-Moderate/Limited,NaN,Email,Within the Service Target,ashley.njau,action failed sur G2,ServiceDesk OPS-XFNC SD
2,INC003,3-Medium,Service Request,Global,Resolved,NAP PROD,6/2/2026 8:13:40 PM,6/2/2026 8:15:17 PM,1.616667,0.026944,0h 2m,Sowmiya E,3-Moderate/Limited,NaN,Internal - Operational team,Within the Service Target,sowmiya.e,NAP Daily Health Checks for All Markets (HUB/MZ),SIRONAML-L1 OPS-APPL CON
3,INC004,3-Medium,Incident,Brazil,Cancelled,PROD BR,6/2/2026 7:20:40 PM,6/2/2026 7:24:34 PM,3.900000,0.065000,0h 4m,Ashley Njau,3-Moderate/Limited,NaN,Monitoring Event,Within the Service Target,ashley.njau,[prrptdb1b_ogg | The lag of process exceeds th...,ServiceDesk OPS-XFNC SD
4,INC005,3-Medium,Incident,Australia,In Progress,SMARTPHONE PROD AU,6/2/2026 5:24:14 PM,NaN,NaN,NaN,NaN,BALAJI SANKAR,3-Moderate/Limited,NaN,Monitoring Event,Within the Service Target,victoria.nzisa,P-2606291 Multiple service problems,One Ops Monitoring GA Consumer

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8825 entries, 0 to 8824
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Incident ID               8825 non-null   object
 1   Priority                  8825 non-null   object
 2   Incident Type             8825 non-null   object
 3   Country                   8825 non-null   object
 4   Status                    8825 non-null   object
 5   Service                   8825 non-null   object
 6   Reported Date             8825 non-null   object
 7   Resolved Date             8552 non-null   object
 8   Resolution Time(Minutes)  8551 non-null   float64
 9   Resolution Time(Hours)    8551 non-null   float64
 10  Resolution hours          8551 non-null   object
 11  Assignee                  8726 non-null   object
 12  Impact                    8825 non-null   object
 13  OldPriority               451 non-null    object
 14  Reported Source           8329 non-null   object
 15  SLM Real Time Status      8424 non-null   object
 16  Submitter*                8825 non-null   object
 17  Summary*                  8825 non-null   object
 18  Support Group Name        8811 non-null   object
dtypes: float64(2), object(17)
memory usage: 1.3+ MB

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8825 entries, 0 to 8824
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   incident_id               8825 non-null   object
 1   priority                  8825 non-null   object
 2   incident_type             8825 non-null   object
 3   country                   8825 non-null   object
 4   status                    8825 non-null   object
 5   service                   8825 non-null   object
 6   reported_date             8825 non-null   object
 7   resolved_date             8552 non-null   object
 8   resolution_time(minutes)  8551 non-null   float64
 9   resolution_time(hours)    8551 non-null   float64
 10  resolution_hours          8551 non-null   object
 11  assignee                  8726 non-null   object
 12  impact                    8825 non-null   object
 13  oldpriority               451 non-null    object
 14  reported_source           8329 non-null   object
 15  slm_real_time_status      8424 non-null   object
 16  submitter*                8825 non-null   object
 17  summary*                  8825 non-null   object
 18  support_group_name        8811 non-null   object
dtypes: float64(2), object(17)
memory usage: 1.3+ MB

In [ ]:
df["reported_date"] = pd.to_datetime(df["reported_date"], errors="coerce")

/tmp/ipykernel_10673/540719305.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["reported_date"] = pd.to_datetime(df["reported_date"], errors="coerce")

In [ ]:
df["resolved_date"] = pd.to_datetime(df["resolved_date"], errors="coerce")

/tmp/ipykernel_10673/2037684373.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["resolved_date"] = pd.to_datetime(df["resolved_date"], errors="coerce")

In [ ]:
df.dtypes

incident_id                         object
priority                            object
incident_type                       object
country                             object
status                              object
service                             object
reported_date               datetime64[ns]
resolved_date               datetime64[ns]
resolution_time(minutes)           float64
resolution_time(hours)             float64
resolution_hours                    object
assignee                            object
impact                              object
oldpriority                         object
reported_source                     object
slm_real_time_status                object
submitter*                          object
summary*                            object
support_group_name                  object
dtype: object

In [ ]:
df["resolution_time(hours)"].mean()

np.float64(60.593266349614886)

1. Which team that gets most tickets?

In [ ]:
team_counts = df["support_group_name"].value_counts()
print(team_counts)

support_group_name
One Ops Monitoring GA Consumer                        3094
Public Cloud Managed Services OPS-INFRA CLD           1111
ServiceDesk OPS-XFNC SD                                942
SIRONAML-L1 OPS-APPL CON                               818
CPS-L1 OPS-APPL CON                                    690
SmartApp And Merchant App L1 OPS-APPL CON              377
QR Code L2 SupportOPS-APPL CON                         326
UAM OPS-APPL CON                                       294
SmartApp And Merchant App L2 OPS-APPL CON              251
HUBL1 OPS-APPL CON                                     174
CS-L1 OPS-APPL CON                                     164
Mobile Services SD OPS-EG                              112
Security                                                95
G2 2nd Level Support (Huawei) OPS-APPL CON              80
Mobile Services SD OPS-VFBR                             76
Support OPS-AU                                          63
Mobile Payment Operations Consumer L3 OPS-APPL CON      46
Mobile Payment Operations Consumer OPS-APPL CON         34
SIRONAML-L2 OPS-APPL CON                                29
LMP-L1 OPS-APPL CON                                     29
Mobile Services OPS-CH                                   3
System ITSM                                              1
SMC Monitoring TSSC                                      1
Live Chat support OPS-APPL CON                           1
Name: count, dtype: int64

2. Which service has the most tickets?

In [ ]:
service_counts = df["service"].value_counts()
print(service_counts)

service
QR CODE PROD                1262
PROD BR                      753
NAP PROD                     694
PROD CH                      580
HUB-PROD                     579
PROD AU                      508
SMARTPHONE PROD EG           508
PROD FR                      497
PROD EG                      496
SMARTPHONE PROD AU           325
BUSINESS APP PROD EG         272
SMARTPHONE PROD BR           231
NAP PROD SN                  220
NAP PROD BR                  205
SMARTPHONE PROD CH           198
BUSINESS APP PROD CH         189
PROD                         176
NAP PROD AU                  168
EKYC PROD                    161
NAP PROD EG                  139
HUB-LMP                      123
NAP PROD FR                  102
FINTECH-PROD EG               71
CS PRIVATE CLOUD PROD         58
OAT FR                        39
NAP PROD CH                   38
HUB-NAP                       30
ONECODE SMARTAPP-PROD EG      22
UAT BR                        22
UAT AU                        21
UAT FR                        19
OAT AU                        16
OAT BR                        13
DR CH                         13
SMARTPHONE OAT CH             12
BUSINESS APP OAT EG            9
BUSINESS APP OAT CH            9
OAT EG                         9
UAT EG                         6
HUB-MFT                        3
AML PROD CH                    3
AML PROD EG                    3
NAP RTS PROD                   3
DR BR                          2
SMARTPHONE UAT AU              2
SMARTPHONE OAT EG              2
SMARTPHONE OAT BR              2
SMARTPHONE UAT BR              2
TEST                           2
SMARTPHONE OAT AU              2
UAT CH                         2
DR FR                          1
CS-PROD EG                     1
AML PROD FR                    1
AML DAD                        1
Name: count, dtype: int64

3. Which service has the most incidents?

In [ ]:
incidents_counts = df[df["incident_type"] == "Incident"]["service"].value_counts()
print(incidents_counts)

service
QR CODE PROD                1111
SMARTPHONE PROD EG           376
PROD CH                      293
SMARTPHONE PROD AU           280
HUB-PROD                     240
PROD EG                      232
PROD AU                      190
PROD FR                      174
BUSINESS APP PROD EG         149
NAP PROD AU                  137
PROD BR                      129
NAP PROD EG                  125
SMARTPHONE PROD BR            92
NAP PROD FR                   88
SMARTPHONE PROD CH            77
FINTECH-PROD EG               66
BUSINESS APP PROD CH          61
CS PRIVATE CLOUD PROD         33
NAP PROD SN                   29
HUB-NAP                       27
NAP PROD BR                   27
NAP PROD CH                   26
NAP PROD                      23
ONECODE SMARTAPP-PROD EG      22
UAT AU                        20
UAT FR                        18
DR CH                         13
HUB-LMP                       10
OAT FR                         9
OAT AU                         5
PROD                           4
UAT BR                         4
UAT EG                         4
AML PROD CH                    3
NAP RTS PROD                   3
AML PROD EG                    3
SMARTPHONE UAT AU              2
HUB-MFT                        2
SMARTPHONE UAT BR              2
EKYC PROD                      1
DR FR                          1
SMARTPHONE OAT AU              1
DR BR                          1
AML PROD FR                    1
OAT BR                         1
Name: count, dtype: int64

4. Which service has the most service requests?

In [ ]:
SR_counts = df[df["incident_type"] == "Service Request"]["service"].value_counts()
print(SR_counts)

service
NAP PROD                 671
PROD BR                  624
HUB-PROD                 339
PROD FR                  323
PROD AU                  318
PROD CH                  287
PROD EG                  264
NAP PROD SN              191
NAP PROD BR              178
PROD                     172
EKYC PROD                160
QR CODE PROD             151
SMARTPHONE PROD BR       139
SMARTPHONE PROD EG       132
BUSINESS APP PROD CH     128
BUSINESS APP PROD EG     123
SMARTPHONE PROD CH       121
HUB-LMP                  113
SMARTPHONE PROD AU        45
NAP PROD AU               31
OAT FR                    30
CS PRIVATE CLOUD PROD     25
UAT BR                    18
NAP PROD EG               14
NAP PROD FR               14
NAP PROD CH               12
OAT BR                    12
SMARTPHONE OAT CH         12
OAT AU                    11
BUSINESS APP OAT EG        9
BUSINESS APP OAT CH        9
OAT EG                     9
FINTECH-PROD EG            5
HUB-NAP                    3
SMARTPHONE OAT EG          2
SMARTPHONE OAT BR          2
UAT CH                     2
TEST                       2
UAT EG                     2
CS-PROD EG                 1
UAT AU                     1
UAT FR                     1
SMARTPHONE OAT AU          1
HUB-MFT                    1
DR BR                      1
AML DAD                    1
Name: count, dtype: int64

In [ ]:
category_counts = df.groupby("incident_type")["service"].value_counts()
print(category_counts)

incident_type    service
Incident         QR CODE PROD          1111
                 SMARTPHONE PROD EG     376
                 PROD CH                293
                 SMARTPHONE PROD AU     280
                 HUB-PROD               240
                                       ...
Service Request  DR BR                    1
                 HUB-MFT                  1
                 SMARTPHONE OAT AU        1
                 UAT AU                   1
                 UAT FR                   1
Name: count, Length: 91, dtype: int64

In [ ]:
pivot = df.pivot_table(
    index="service",
    columns="incident_type",
    aggfunc="size",
    fill_value=0
)

print(pivot)

incident_type             Incident  Service Request
service
AML DAD                          0                1
AML PROD CH                      3                0
AML PROD EG                      3                0
AML PROD FR                      1                0
BUSINESS APP OAT CH              0                9
BUSINESS APP OAT EG              0                9
BUSINESS APP PROD CH            61              128
BUSINESS APP PROD EG           149              123
CS PRIVATE CLOUD PROD           33               25
CS-PROD EG                       0                1
DR BR                            1                1
DR CH                           13                0
DR FR                            1                0
EKYC PROD                        1              160
FINTECH-PROD EG                 66                5
HUB-LMP                         10              113
HUB-MFT                          2                1
HUB-NAP                         27                3
HUB-PROD                       240              339
NAP PROD                        23              671
NAP PROD AU                    137               31
NAP PROD BR                     27              178
NAP PROD CH                     26               12
NAP PROD EG                    125               14
NAP PROD FR                     88               14
NAP PROD SN                     29              191
NAP RTS PROD                     3                0
OAT AU                           5               11
OAT BR                           1               12
OAT EG                           0                9
OAT FR                           9               30
ONECODE SMARTAPP-PROD EG        22                0
PROD                             4              172
PROD AU                        190              318
PROD BR                        129              624
PROD CH                        293              287
PROD EG                        232              264
PROD FR                        174              323
QR CODE PROD                  1111              151
SMARTPHONE OAT AU                1                1
SMARTPHONE OAT BR                0                2
SMARTPHONE OAT CH                0               12
SMARTPHONE OAT EG                0                2
SMARTPHONE PROD AU             280               45
SMARTPHONE PROD BR              92              139
SMARTPHONE PROD CH              77              121
SMARTPHONE PROD EG             376              132
SMARTPHONE UAT AU                2                0
SMARTPHONE UAT BR                2                0
TEST                             0                2
UAT AU                          20                1
UAT BR                           4               18
UAT CH                           0                2
UAT EG                           4                2
UAT FR                          18                1

4. SLA non-breach count

In [ ]:
sla_non_breach = df[df["slm_real_time_status"] == "Within the Service Target"]["country"].value_counts()
print(sla_non_breach)

country
Global                        2938
Egypt                         1356
China                         1146
Brazil                        1019
Australia                      898
France                         582
Singapore                       53
Group Services Limited SSC      13
Italy                            1
Group Services Limited           1
Name: count, dtype: int64

5. SLA breached count

In [ ]:
country_breached = df[df["slm_real_time_status"] == "Service Targets Breached"]["country"].value_counts()
print(country_breached)

country
Global       167
Egypt        105
Australia     47
Brazil        24
France        24
China         16
Singapore      2
Name: count, dtype: int64

In [ ]:
df["slm_real_time_status"].value_counts()

slm_real_time_status
Within the Service Target    8007
Service Targets Breached      385
Service Target Warning         32
Name: count, dtype: int64

6. Pivot table for country vs status

In [ ]:
country_pivot = df.pivot_table(index="country",columns="status",aggfunc="size",fill_value=0)
print(country_pivot)

status                      Assigned  Cancelled  In Progress  Pending  \
country
Australia                          9          3            7        6
Brazil                            11          5           14       11
China                              7          1           11       14
Egypt                             19          3           18       27
France                             6          7           12        8
Global                            50          9           30       11
Group Services Limited             0          0            0        0
Group Services Limited SSC         0          2            0        0
Italy                              0          0            0        0
Singapore                          0          0            1        2

status                      Resolved
country
Australia                        939
Brazil                          1209
China                           1145
Egypt                           1442
France                           585
Global                          3135
Group Services Limited             1
Group Services Limited SSC        11
Italy                              1
Singapore                         53

In [ ]:
!pip install --upgrade ipython-sql prettytable

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (3.17.0)
Collecting prettytable
  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.50)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable) (0.8.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Collecting jedi>=0.16 (from ipython->ipython-sql)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Downloading prettytable-3.18.0-py3-none-any.whl (37 kB)
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 50.2 MB/s eta 0:00:00
Installing collected packages: prettytable, jedi
  Attempting uninstall: prettytable
    Found existing installation: prettytable 3.17.0
    Uninstalling prettytable-3.17.0:
      Successfully uninstalled prettytable-3.17.0
Successfully installed jedi-0.20.0 prettytable-3.18.0

In [ ]:
import sqlite3
conn = sqlite3.connect("test.db")

%load_ext sql
%sql sqlite:///test.db

In [ ]:
df.to_sql("incidents", conn, if_exists="replace")

8825

In [ ]:
#Show all records in the dataset.
pd.read_sql("SELECT * FROM incidents",conn)

,index,incident_id,priority,incident_type,country,status,service,reported_date,resolved_date,resolution_time(minutes),resolution_time(hours),resolution_hours,assignee,impact,oldpriority,reported_source,slm_real_time_status,submitter*,summary*,support_group_name
0,0,INC001,3-Medium,Incident,Australia,Resolved,NAP PROD AU,2026-06-02 20:31:40,2026-06-02 20:54:42,23.033333,0.383889,0h 23m,Sowmiya E,3-Moderate/Limited,None,Monitoring Event,Within the Service Target,ashley.njau,CMOZ | Delta scoring is running longer than usual,ServiceDesk OPS-XFNC SD
1,1,INC002,3-Medium,Incident,Brazil,Assigned,PROD BR,2026-06-02 20:21:18,None,NaN,NaN,None,None,3-Moderate/Limited,None,Email,Within the Service Target,ashley.njau,action failed sur G2,ServiceDesk OPS-XFNC SD
2,2,INC003,3-Medium,Service Request,Global,Resolved,NAP PROD,2026-06-02 20:13:40,2026-06-02 20:15:17,1.616667,0.026944,0h 2m,Sowmiya E,3-Moderate/Limited,None,Internal - Operational team,Within the Service Target,sowmiya.e,NAP Daily Health Checks for All Markets (HUB/MZ),SIRONAML-L1 OPS-APPL CON
3,3,INC004,3-Medium,Incident,Brazil,Cancelled,PROD BR,2026-06-02 19:20:40,2026-06-02 19:24:34,3.900000,0.065000,0h 4m,Ashley Njau,3-Moderate/Limited,None,Monitoring Event,Within the Service Target,ashley.njau,[prrptdb1b_ogg | The lag of process exceeds th...,ServiceDesk OPS-XFNC SD
4,4,INC005,3-Medium,Incident,Australia,In Progress,SMARTPHONE PROD AU,2026-06-02 17:24:14,None,NaN,NaN,None,BALAJI SANKAR,3-Moderate/Limited,None,Monitoring Event,Within the Service Target,victoria.nzisa,P-2606291 Multiple service problems,One Ops Monitoring GA Consumer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8820,8820,INC8821,3-Medium,Service Request,Egypt,Resolved,SMARTPHONE PROD EG,2026-01-01 09:16:36,2026-01-01 09:23:13,6.616667,0.110278,0h 7m,Yuvashree R,3-Moderate/Limited,None,Email,Within the Service Target,yuvashree.r,TZ Smartapp Health Checks (01-01-2025),SmartApp And Merchant App L2 OPS-APPL CON
8821,8821,INC8822,3-Medium,Service Request,Australia,Resolved,SMARTPHONE PROD AU,2026-01-01 09:12:25,2026-01-01 12:07:20,174.916667,2.915278,2h 55m,Vasanth Kumar,3-Moderate/Limited,None,Web to ticket,Within the Service Target,vasanth.kumar1,MZ Smartapp Health Checks (01-01-2026),SmartApp And Merchant App L2 OPS-APPL CON
8822,8822,INC8823,3-Medium,Service Request,Global,Resolved,NAP PROD,2026-01-01 06:08:51,2026-01-01 07:04:02,55.183333,0.919722,0h 55m,Diana Kalema,3-Moderate/Limited,None,Internal - Operational team,Within the Service Target,diana.kalema,NAP Daily health Checks for All Markets (HUB/M...,One Ops Monitoring GA Consumer
8823,8823,INC8824,3-Medium,Incident,Australia,Resolved,NAP PROD AU,2026-01-01 02:44:15,2026-01-01 07:31:14,286.983333,4.783056,4h 47m,Diana Kalema,3-Moderate/Limited,None,Email,Within the Service Target,moreen.kariuki,CMOZ | GWSKOPR Process stuck,One Ops Monitoring GA Consumer
8824,8824,INC8825,3-Medium,Incident,Egypt,Resolved,PROD EG,2026-01-01 01:13:39,2026-01-02 10:21:49,1988.166667,33.136111,33h 8m,Gerald Nderitu,1-Extensive/Widespread,None,Monitoring Event,Within the Service Target,moreen.kariuki,OGG_104_prrptdb2a | The lag of process exceeds...,One Ops Monitoring GA Consumer

In [ ]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%config SqlMagic.displaylimit = 10

In [ ]:
#Show first 10 rows of the data
%sql SELECT * FROM incidents LIMIT 10;

 * sqlite:///test.db
Done.

[(0, 'INC001', '3-Medium', 'Incident', 'Australia', 'Resolved', 'NAP PROD AU', '2026-06-02 20:31:40', '2026-06-02 20:54:42', 23.0333333322778, 0.383888888871297, '0h 23m', 'Sowmiya E', '3-Moderate/Limited', None, 'Monitoring Event', 'Within the Service Target', 'ashley.njau', 'CMOZ | Delta scoring is running longer than usual', 'ServiceDesk OPS-XFNC SD'),
 (1, 'INC002', '3-Medium', 'Incident', 'Brazil', 'Assigned', 'PROD BR', '2026-06-02 20:21:18', None, None, None, None, None, '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ashley.njau', 'action failed sur G2', 'ServiceDesk OPS-XFNC SD'),
 (2, 'INC003', '3-Medium', 'Service Request', 'Global', 'Resolved', 'NAP PROD', '2026-06-02 20:13:40', '2026-06-02 20:15:17', 1.6166666673962, 0.0269444444566034, '0h 2m', 'Sowmiya E', '3-Moderate/Limited', None, 'Internal - Operational team', 'Within the Service Target', 'sowmiya.e', 'NAP Daily Health Checks for All Markets (HUB/MZ)', 'SIRONAML-L1 OPS-APPL CON'),
 (3, 'INC004', '3-Medium', 'Incident', 'Brazil', 'Cancelled', 'PROD BR', '2026-06-02 19:20:40', '2026-06-02 19:24:34', 3.9000000001397, 0.0650000000023283, '0h 4m', 'Ashley Njau', '3-Moderate/Limited', None, 'Monitoring Event', 'Within the Service Target', 'ashley.njau', '[prrptdb1b_ogg | The lag of process exceeds the threshold of LAGCRITICALSECONDS]', 'ServiceDesk OPS-XFNC SD'),
 (4, 'INC005', '3-Medium', 'Incident', 'Australia', 'In Progress', 'SMARTPHONE PROD AU', '2026-06-02 17:24:14', None, None, None, None, 'BALAJI SANKAR', '3-Moderate/Limited', None, 'Monitoring Event', 'Within the Service Target', 'victoria.nzisa', 'P-2606291     Multiple service problems', 'One Ops Monitoring GA Consumer'),
 (5, 'INC006', '3-Medium', 'Incident', 'Global', 'Assigned', 'HUB-PROD', '2026-06-02 18:05:09', None, None, None, None, None, '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ian.macharia', 'Unable to Connect to Techno Center Proxy 2 Server via MPA CyberArk', 'One Ops Monitoring GA Consumer'),
 (6, 'INC007', '3-Medium', 'Service Request', 'China', 'In Progress', 'SMARTPHONE PROD CH', '2026-06-02 17:03:59', None, None, None, None, 'Pavithra M', '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ian.macharia', 'SMSC accounts', 'One Ops Monitoring GA Consumer'),
 (7, 'INC008', '3-Medium', 'Service Request', 'China', 'In Progress', 'CS PRIVATE CLOUD PROD', '2026-06-02 16:43:44', None, None, None, None, 'cliffe owino', '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ian.macharia', 'SMSC accounts', 'One Ops Monitoring GA Consumer'),
 (8, 'INC009', '3-Medium', 'Incident', 'Singapore', 'In Progress', 'NAP PROD SN', '2026-06-02 16:30:09', None, None, None, None, 'Diana Kalema', '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ian.macharia', 'Spike Siron KYC alerts - Beneficial Owner', 'One Ops Monitoring GA Consumer'),
 (9, 'INC010', '3-Medium', 'Service Request', 'China', 'In Progress', 'BUSINESS APP PROD CH', '2026-06-02 17:07:15', None, None, None, None, 'Pavithra M', '3-Moderate/Limited', None, 'Email', 'Within the Service Target', 'ian.macharia', 'SMSC accounts', 'One Ops Monitoring GA Consumer')]

In [ ]:
# How many total tickets are there?
%sql SELECT COUNT(*) FROM incidents;

 * sqlite:///test.db
Done.

[(8825,)]

In [32]:
# Number of incidents
%sql SELECT COUNT(*) FROM incidents WHERE incident_type = "Incident";

 * sqlite:///test.db
Done.

[(4115,)]

In [31]:
# Show the number of unique services
%sql SELECT DISTINCT service FROM incidents;

 * sqlite:///test.db
Done.

[('NAP PROD AU',),
 ('PROD BR',),
 ('NAP PROD',),
 ('SMARTPHONE PROD AU',),
 ('HUB-PROD',),
 ('SMARTPHONE PROD CH',),
 ('CS PRIVATE CLOUD PROD',),
 ('NAP PROD SN',),
 ('BUSINESS APP PROD CH',),
 ('PROD CH',),
 ('FINTECH-PROD EG',),
 ('NAP PROD BR',),
 ('PROD AU',),
 ('PROD EG',),
 ('HUB-LMP',),
 ('SMARTPHONE PROD EG',),
 ('PROD FR',),
 ('BUSINESS APP OAT EG',),
 ('BUSINESS APP OAT CH',),
 ('OAT FR',),
 ('QR CODE PROD',),
 ('EKYC PROD',),
 ('BUSINESS APP PROD EG',),
 ('SMARTPHONE OAT CH',),
 ('NAP PROD EG',),
 ('HUB-NAP',),
 ('SMARTPHONE PROD BR',),
 ('NAP PROD FR',),
 ('PROD',),
 ('OAT AU',),
 ('SMARTPHONE OAT EG',),
 ('NAP PROD CH',),
 ('ONECODE SMARTAPP-PROD EG',),
 ('UAT AU',),
 ('OAT BR',),
 ('DR CH',),
 ('SMARTPHONE UAT AU',),
 ('UAT BR',),
 ('DR FR',),
 ('UAT FR',),
 ('CS-PROD EG',),
 ('OAT EG',),
 ('NAP RTS PROD',),
 ('UAT EG',),
 ('SMARTPHONE OAT BR',),
 ('HUB-MFT',),
 ('TEST',),
 ('AML PROD CH',),
 ('SMARTPHONE OAT AU',),
 ('UAT CH',),
 ('AML PROD EG',),
 ('DR BR',),
 ('SMARTPHONE UAT BR',),
 ('AML PROD FR',),
 ('AML DAD',)]

In [34]:
# Number of service requests
%sql SELECT COUNT(*) FROM incidents WHERE incident_type="Service Request"

 * sqlite:///test.db
Done.

[(4710,)]

In [35]:
# Number of tickets per service
%sql SELECT incident_type, COUNT(*) FROM incidents GROUP BY incident_type

 * sqlite:///test.db
Done.

[('Incident', 4115), ('Service Request', 4710)]

In [37]:
# Number of tickets per SLA status
%sql SELECT slm_real_time_status, COUNT(*) FROM incidents GROUP BY slm_real_time_status

 * sqlite:///test.db
Done.

[(None, 401),
 ('Service Target Warning', 32),
 ('Service Targets Breached', 385),
 ('Within the Service Target', 8007)]

In [41]:
# Services with top 5 number of tickets
%sql SELECT service, COUNT(*) as total FROM incidents GROUP BY "service" ORDER BY total DESC LIMIT 5;

 * sqlite:///test.db
Done.

[('QR CODE PROD', 1262),
 ('PROD BR', 753),
 ('NAP PROD', 694),
 ('PROD CH', 580),
 ('HUB-PROD', 579)]

In [44]:
# Find average resolution time
%sql SELECT AVG("resolution_time(hours)") FROM incidents

 * sqlite:///test.db
Done.

[(60.593266349614886,)]

In [49]:
# Find average resolution time per service
%sql SELECT service, AVG("resolution_time(hours)") as average FROM incidents GROUP BY service ORDER BY average DESC

 * sqlite:///test.db
Done.

[('SMARTPHONE OAT EG', 1322.37749999994),
 ('OAT FR', 403.49125420877317),
 ('OAT EG', 281.6700000000415),
 ('PROD', 217.66894683026436),
 ('UAT BR', 203.68956349208014),
 ('ONECODE SMARTAPP-PROD EG', 200.8844097222245),
 ('SMARTPHONE OAT BR', 193.30833333331992),
 ('UAT EG', 180.57717592592226),
 ('OAT BR', 176.63021367527725),
 ('FINTECH-PROD EG', 170.6620238095084),
 ('OAT AU', 159.3791666666743),
 ('HUB-PROD', 132.33820946657943),
 ('CS PRIVATE CLOUD PROD', 127.51074252137347),
 ('PROD FR', 122.66789599347997),
 ('PROD EG', 120.15414767331394),
 ('NAP PROD EG', 120.03652777777658),
 ('HUB-NAP', 106.3513888888858),
 ('NAP RTS PROD', 106.24847222227231),
 ('UAT FR', 102.20444444443757),
 ('SMARTPHONE UAT AU', 97.30013888888084),
 ('AML PROD EG', 97.21231481479496),
 ('HUB-MFT', 74.4757407407742),
 ('PROD BR', 73.17873803009961),
 ('SMARTPHONE OAT AU', 72.4727777777589),
 ('UAT AU', 66.65123456789301),
 ('PROD AU', 58.816700133865325),
 ('PROD CH', 57.75850978647474),
 ('NAP PROD AU', 57.044811447807156),
 ('SMARTPHONE PROD BR', 50.69421026407325),
 ('SMARTPHONE OAT CH', 47.54224537036496),
 ('SMARTPHONE UAT BR', 46.890000000014),
 ('NAP PROD CH', 46.22368464053108),
 ('AML PROD CH', 45.71462962962687),
 ('SMARTPHONE PROD EG', 44.933591627700764),
 ('SMARTPHONE PROD CH', 43.835509736535556),
 ('HUB-LMP', 37.245534188036466),
 ('NAP PROD FR', 33.71558580858434),
 ('SMARTPHONE PROD AU', 31.01878232005621),
 ('BUSINESS APP PROD EG', 29.083359053499432),
 ('AML PROD FR', 28.4824999999255),
 ('NAP PROD SN', 26.387057849137157),
 ('DR BR', 24.51333333336513),
 ('BUSINESS APP PROD CH', 23.510335401892583),
 ('DR FR', 22.8058333334047),
 ('NAP PROD BR', 21.692599106644117),
 ('BUSINESS APP OAT CH', 11.167283950664572),
 ('QR CODE PROD', 10.16227971627447),
 ('NAP PROD', 8.63679792871034),
 ('BUSINESS APP OAT EG', 3.823827160483535),
 ('DR CH', 3.5395299145334005),
 ('EKYC PROD', 3.182668402774654),
 ('UAT CH', 2.1784722222655546),
 ('TEST', 0.0252777777495794),
 ('CS-PROD EG', None),
 ('AML DAD', None)]